# Generated by Django 6.0.6 on 2026-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='unknown', max_length=100)),
                ('course', models.CharField(choices=[('ai & prompt engineering', 'AI & Prompt Engineering'), ('python programming', 'Python Programming'), ('web developer', 'Web Developer')], max_length=100)),
                ('files', models.FileField(upload_to='userfiles/')),
            ],
        ),
    ]
